export const moduleMeta = {
  superadmin: { title: 'Superadmin', subtitle: 'Platform-wide control center' },
  dashboard: { title: 'Hospital Dashboard', subtitle: 'Operational overview' },
  doctor_workspace: { title: 'Doctor Desk', subtitle: 'Today\'s appointments & patients' },
  patients: { title: 'OP&IP Registration', subtitle: 'Demographics and clinical folders' },
  appointments: { title: 'OPD Scheduling', subtitle: 'Doctor bookings & walk-ins' },
  emr: { title: 'Clinical Desk / EMR', subtitle: 'Diagnosis, history & e-Prescription' },
  inpatient: { title: 'IPD / Bed Management', subtitle: 'Admission, Ward & Bed tracker' },
  pharmacy: { title: 'Pharmacy / Drug Dispensing', subtitle: 'Prescription fulfillment' },
  billing: { title: 'Cashier & Billing', subtitle: 'Final bills and collections' },
  insurance: { title: 'TPA / Insurance', subtitle: 'Payers, claims and coverage' },
  inventory: { title: 'Central Stores / Inventory', subtitle: 'Stock levels & drug batches' },
  employees: { title: 'HR / Personnel', subtitle: 'Staff shift, salary and leave' },
  reports: { title: 'MIS & Analytics', subtitle: 'Management Information System' },
  admin: { title: 'Facility Settings', subtitle: 'Unit and system configuration' },
  accounts: { title: 'Daybook & Accounts', subtitle: 'Petty cash and ledger' },
  lab: { title: 'Laboratory / Diagnostics', subtitle: 'Test results and reporting' },
  support: { title: 'Unit Maintenance', subtitle: 'Facility assistance' },
  users: { title: 'Access Control', subtitle: 'User Identity & Roles' },
  communication: { title: 'Internal Notice Board', subtitle: 'Staff alerts' },
  documents: { title: 'Records Library', subtitle: 'Digitized health records' }
};

export const fallbackPermissions = {
  Superadmin: ['superadmin', 'dashboard', 'admin', 'reports', 'support'],
  Admin: ['dashboard', 'appointments', 'patients', 'emr', 'inpatient', 'billing', 'insurance', 'inventory', 'pharmacy', 'lab', 'employees', 'accounts', 'reports', 'admin', 'users', 'communication', 'documents'],
  Doctor: ['dashboard', 'appointments', 'patients', 'emr', 'inpatient', 'reports', 'lab', 'pharmacy', 'communication', 'documents'],
  Nurse: ['dashboard', 'appointments', 'patients', 'emr', 'inpatient', 'inventory', 'communication', 'documents'],
  Lab: ['dashboard', 'patients', 'lab', 'reports', 'communication', 'documents'],
  Pharmacy: ['dashboard', 'pharmacy', 'inventory', 'reports', 'communication', 'documents'],
  'Support Staff': ['dashboard', 'inventory', 'support', 'communication'],
  'Front Office': ['dashboard', 'appointments', 'patients', 'billing', 'inpatient', 'communication', 'documents'],
  Billing: ['dashboard', 'billing', 'accounts', 'insurance', 'reports'],
  Insurance: ['dashboard', 'insurance', 'reports'],
  HR: ['dashboard', 'employees', 'reports', 'communication', 'documents'],
  Accounts: ['dashboard', 'billing', 'accounts', 'insurance', 'reports'],
  Management: ['dashboard', 'reports', 'employees', 'billing', 'accounts', 'insurance', 'inpatient', 'communication', 'documents'],
  Inventory: ['dashboard', 'inventory', 'pharmacy', 'reports'],
  Auditor: ['dashboard', 'reports'],
  Patient: ['dashboard', 'appointments', 'patients']
};
