-- DISABLED: 005_fhir_compliance.sql
-- This migration was disabled because it references tables that should only exist in tenant schemas
-- not in the emr management schema. The tables are created dynamically per tenant.
-- Original file backed up as 005_fhir_compliance.sql.backup
